### ISSUE TITLE
Distance function.

### ISSUE THREAD

**Issue by Soldy** [ranon-rat/monkeyPage#1]
Can i help?

**Comment by ranon-rat** [comment]
yeah , i dont have a problem with that

**Comment by ranon-rat** [comment]
if you want to contact me maybe you can go to my discord server, sorry for my bad english

**Comment by Soldy** [comment]
I just have an idea how you can improve this.

```
try┆this
```

**Comment by ranon-rat** [comment]
okay thanks for that
